name = "SimplePhaseDiagrams"
uuid = "850957da-f65d-4214-a547-37cf00579af1"
authors = ["singularitti <singularitti@outlook.com> and contributors"]
version = "1.0.0-DEV"

[deps]
DataInterpolations = "82cc6244-b520-54b8-b5a6-8a565e85f1d0"

[compat]
julia = "1"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
